[issues]
max-issues-per-linter = 0
max-same-issues = 0

[linters]
disable-all = true
enable = [
    "asasalint",
    "asciicheck",
    "bidichk",
    "containedctx",
    "decorder",
    "depguard",
    "dogsled",
    "gofmt",
    "gci",
    "dupword",
    "gosimple",
    "govet",
    "ineffassign",
    "staticcheck",
    "typecheck",
    "unused",
    "execinquery",
    "exportloopref",
    "goheader",
    "goimports",
    "gomoddirectives",
    "gomodguard",
    "goprintffuncname",
    "grouper",
    "importas",
    "loggercheck",
    "misspell",
    "nakedret",
    "nolintlint",
    "nosprintfhostport",
    "predeclared",
    "promlinter",
    "reassign",
    "tenv",
    "testableexamples",
    "tparallel",
    "unconvert",
    "usestdlibvars",
    "whitespace",
    "stylecheck",
    "nilerr",
    "nilnil",
    "godot",
    
    # "revive",
    # "noctx",
    # "gosec",
    # "errcheck",
    # "prealloc",
    # "errorlint",
    # "goerr113",
]
