name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run Go linters
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.1
        golangci-lint run ./...

    - name: Build library
      run: |
        go test -v ./...
        go build 